# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 769fb2d935418ba00dd798dde6ec588505650af36687e3e0aa8e73aae749b8cfb1df0ce0f1dafae20e909049ca6efac8f763b72e623c9309d6c571eec8f763df

test:
  secret_key_base: 817c29281196d16df19e9f4244741ff517eade4353530be53d0f78e71d6aa1246cfabc4639b0d4bcad8f5cc5c038b76f0f8deeec6abe77ffcdfdf8a692acda25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
